name: Publish NuGet

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - 'docs/**/*'
      - '**.md'
      - '**.DotSettings'
      - '.idea'
      - '**.scss'
      - '**.toml'
      - '**.html'

jobs:
  nuget:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'
      - name: Create and push NuGet package
        run: |
          dotnet pack -c Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}